# Generated by Django 3.0.7 on 2020-06-24 18:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('languages', models.CharField(choices=[('Visual Basic .NET', 'Visual Basic Net'), ('Objective-C', 'Objective C'), ('JavaScript', 'Javascript'), ('Python', 'Python'), ('C#', 'C Hash'), ('Swift', 'Swift'), ('Java', 'Java'), ('Ruby', 'Ruby'), ('Perl', 'Perl'), ('C++', 'Cpp'), ('PHP', 'Php'), ('SQL', 'Sql'), ('Go', 'Go'), ('C', 'C'), ('R', 'R')], max_length=50)),
                ('fields', models.CharField(choices=[('Desktop App Developer', 'Desktop App'), ('Android App Developer', 'Android App'), ('iOS App Developer', 'Ios App'), ('Web App Developer', 'Web App'), ('Machine Learning', 'Ml'), ('Artificial Intelligence', 'Ai')], max_length=50)),
                ('specialization', models.CharField(choices=[('Front End Developer', 'Fed'), ('Back End Developer', 'Bed'), ('Full Stack Developer', 'Fsd')], max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beg'), ('Experienced', 'Exp'), ('Pro', 'Pro')], max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
