# Generated by Django 3.0.7 on 2020-06-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancer',
            options={'verbose_name': 'Freelancer', 'verbose_name_plural': 'Freelancers'},
        ),
    ]
